<?php

/**
 * @file
 * Hook implementations.
 */

use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\embargo\EmbargoStorage;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_type_alter().
 */
function embargo_entity_type_alter(array &$entity_types) : void {
  $applicable_entity_types = EmbargoStorage::applicableEntityTypes();
  foreach ($applicable_entity_types as $entity_type_id) {
    $entity_type = &$entity_types[$entity_type_id];
    $entity_type->setLinkTemplate('embargoes', "/embargo/$entity_type_id/{{$entity_type_id}}");
  }
}

/**
 * Implements hook_entity_access().
 */
function embargo_entity_access(EntityInterface $entity, $operation, AccountInterface $account) : AccessResultInterface {
  /** @var \Drupal\embargo\Access\EmbargoAccessCheckInterface $service */
  $service = \Drupal::service('access_check.embargo');
  return $service->access($entity, $account);
}

/**
 * Implements hook_file_download().
 */
function embargo_file_download($uri) : null|array|int {
  $files = \Drupal::entityTypeManager()
    ->getStorage('file')
    ->loadByProperties(['uri' => $uri]);
  $file = reset($files);
  if ($file instanceof EntityInterface) {
    $access = \Drupal::service('access_check.embargo')->access($file, \Drupal::currentUser());
    if ($access->isForbidden()) {
      return -1;
    }
  }
}

/**
 * Implements hook_query_TAG_alter() for `node_access` tagged queries.
 */
function embargo_query_node_access_alter(AlterableInterface $query) : void {
  /** @var \Drupal\embargo\Access\QueryTagger $tagger */
  $tagger = \Drupal::service('embargo.query_tagger');
  $tagger->tagNode($query);
}

/**
 * Implements hook_theme().
 */
function embargo_theme($existing, $type, $theme, $path) : array {
  return [
    'embargo_ip_access_exemption' => [
      'template' => 'embargo-ip-access-exemption',
      'variables' => [
        // A list of resource names.
        'resources' => [],
        // A list of embargo_ip_range entity identifers.
        'ranges' => [],
        'contact_email' => NULL,
      ],
    ],
    'embargo_notification' => [
      'template' => 'embargo-notification',
      'variables' => [
        'embargoes' => [],
        'message' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert() for embargo entities.
 */
function embargo_embargo_insert(EntityInterface $entity) : void {
  /** @var \Drupal\embargo\SearchApiTracker $tracker */
  $tracker = \Drupal::service('embargo.search_api_tracker_helper');
  $tracker->track($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update() for embargo entities.
 */
function embargo_embargo_update(EntityInterface $entity) : void {
  /** @var \Drupal\embargo\SearchApiTracker $tracker */
  $tracker = \Drupal::service('embargo.search_api_tracker_helper');
  $tracker->track($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for embargo entities.
 */
function embargo_embargo_delete(EntityInterface $entity) : void {
  /** @var \Drupal\embargo\SearchApiTracker $tracker */
  $tracker = \Drupal::service('embargo.search_api_tracker_helper');
  $tracker->track($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node entities.
 */
function embargo_node_delete(EntityInterface $entity) : void {
  assert($entity instanceof NodeInterface);
  /** @var \Drupal\embargo\SearchApiTracker $tracker */
  $tracker = \Drupal::service('embargo.search_api_tracker_helper');
  $tracker->propagateChildren($entity);
}
