---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    uses: Prashant-bd/phpunit-action/.github/workflows/phpunit.yml@DDST-382
    secrets: inherit
    with:
      composer_patches: |-
        {
          "discoverygarden/islandora_hierarchical_access": {
            "dependent work from dependency": "https://github.com/discoverygarden/islandora_hierarchical_access/pull/19.patch"
          }
        }
