---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    #uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@v1
    uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@adam-vessey-patch-1
    secrets: inherit
    with:
      composer_prereqs: >-
        "discoverygarden/islandora_test_support:dev-adam-vessey-patch-1 as 1.x-dev"
