<?php

/**
 * @file
 * Hook implementations.
 */

/**
 * Implements hook_cron().
 */
function reindex_embargoes_cron(): void {
  $entity_type_manager = \Drupal::entityTypeManager();
  $queue_factory = \Drupal::service('queue');

  $request_time = \Drupal::time()->getRequestTime();
  $next_day = $request_time + 86400;

  $embargo_ids = $entity_type_manager->getStorage('embargo')->getQuery()
    ->accessCheck(FALSE)
    ->condition('embargoed_node', NULL, 'IS NOT NULL')
    ->execute();

  $queue = $queue_factory->get('embargo_expiration_reindex');
  $embargoes = $entity_type_manager->getStorage('embargo')->loadMultiple($embargo_ids);
  foreach ($embargoes as $embargo) {
    $expiration_date = $embargo->getExpirationDate()->getTimestamp();
    if ($expiration_date >= $request_time && $expiration_date < $next_day) {
      $queue->createItem([
        'embargo_id' => $embargo->id(),
      ]);
    }
  }
}
