<?php

/**
 * @file
 * Hook implementations.
 */

use Drupal\Component\Datetime\TimeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;

function _reindex_embargoes_queue_embargo(EntityInterface $entity, QueueFactory $queue_factory, TimeInterface $time): void {
  $expiration_date = $entity->getExpirationDate();
  if (!$expiration_date || !$expiration_date->getTimestamp()) {
    return;
  }

  $expiration_timestamp = $expiration_date->getTimestamp();
  $current_timestamp = $time->getRequestTime();

  if ($expiration_timestamp > $current_timestamp) {
    $queue = $queue_factory->get('embargo_expiration_reindex', TRUE);

    $item = ['embargo_id' => $entity->id()];

    $queue->createItem($item);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function reindex_embargoes_embargo_insert(EntityInterface $entity): void {
  $queue_factory = \Drupal::service('queue');
  $time = \Drupal::service('datetime.time');
  _reindex_embargoes_queue_embargo($entity, $queue_factory, $time);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function reindex_embargoes_embargo_update(EntityInterface $entity): void {
  $queue_factory = \Drupal::service('queue');
  $time = \Drupal::service('datetime.time');
  _reindex_embargoes_queue_embargo($entity, $queue_factory, $time);
}
